{{- if .Values.productService.autoscaling.enabled }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "ecommerce.fullname" . }}-product-service-hpa
  labels:
    {{- include "ecommerce.labels" . | nindent 4 }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "ecommerce.fullname" . }}-product-service
  minReplicas: {{ .Values.productService.autoscaling.minReplicas }}
  maxReplicas: {{ .Values.productService.autoscaling.maxReplicas }}
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: {{ .Values.productService.autoscaling.targetCPUUtilizationPercentage }}
{{- end }}

---
{{- if .Values.userService.autoscaling.enabled }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "ecommerce.fullname" . }}-user-service-hpa
  labels:
    {{- include "ecommerce.labels" . | nindent 4 }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "ecommerce.fullname" . }}-user-service
  minReplicas: {{ .Values.userService.autoscaling.minReplicas }}
  maxReplicas: {{ .Values.userService.autoscaling.maxReplicas }}
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: {{ .Values.userService.autoscaling.targetCPUUtilizationPercentage }}
{{- end }}

---
{{- if .Values.frontendService.autoscaling.enabled }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "ecommerce.fullname" . }}-frontend-service-hpa
  labels:
    {{- include "ecommerce.labels" . | nindent 4 }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "ecommerce.fullname" . }}-frontend-service
  minReplicas: {{ .Values.frontendService.autoscaling.minReplicas }}
  maxReplicas: {{ .Values.frontendService.autoscaling.maxReplicas }}
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: {{ .Values.frontendService.autoscaling.targetCPUUtilizationPercentage }}
{{- end }}