{{- if .Values.secrets.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "ecommerce.fullname" . }}-secrets
  labels:
    {{- include "ecommerce.labels" . | nindent 4 }}
type: Opaque
stringData:
  postgres-password: {{ .Values.secrets.postgres.password | quote }}
  rabbitmq-password: {{ .Values.secrets.rabbitmq.password | quote }}
  jwt-secret: {{ .Values.secrets.jwt.secret | quote }}
{{- end }}